# Generated by Django 5.0.1 on 2024-01-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_redactor_years_of_experiments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_newspapers', to='agency.topic'),
        ),
    ]
